# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from costmap_layers/Wall.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Wall(genpy.Message):
  _md5sum = "68c0f9e0fd6bb3eb2070700be3dd1d6a"
  _type = "costmap_layers/Wall"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string identifier
geometry_msgs/Point from
geometry_msgs/Point to
int32 width


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['identifier','from_','to','width']
  _slot_types = ['string','geometry_msgs/Point','geometry_msgs/Point','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       identifier,from_,to,width

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Wall, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.identifier is None:
        self.identifier = ''
      if self.from_ is None:
        self.from_ = geometry_msgs.msg.Point()
      if self.to is None:
        self.to = geometry_msgs.msg.Point()
      if self.width is None:
        self.width = 0
    else:
      self.identifier = ''
      self.from_ = geometry_msgs.msg.Point()
      self.to = geometry_msgs.msg.Point()
      self.width = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.identifier
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6di.pack(_x.from_.x, _x.from_.y, _x.from_.z, _x.to.x, _x.to.y, _x.to.z, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.from_ is None:
        self.from_ = geometry_msgs.msg.Point()
      if self.to is None:
        self.to = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.identifier = str[start:end].decode('utf-8')
      else:
        self.identifier = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.from_.x, _x.from_.y, _x.from_.z, _x.to.x, _x.to.y, _x.to.z, _x.width,) = _struct_6di.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.identifier
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6di.pack(_x.from_.x, _x.from_.y, _x.from_.z, _x.to.x, _x.to.y, _x.to.z, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.from_ is None:
        self.from_ = geometry_msgs.msg.Point()
      if self.to is None:
        self.to = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.identifier = str[start:end].decode('utf-8')
      else:
        self.identifier = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.from_.x, _x.from_.y, _x.from_.z, _x.to.x, _x.to.y, _x.to.z, _x.width,) = _struct_6di.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6di = struct.Struct("<6di")
